/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/email-sent`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-a` | `/treino-a`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-b` | `/treino-b`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-c` | `/treino-c`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-d` | `/treino-d`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/email-sent`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/treino-a` | `/treino-a`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/treino-b` | `/treino-b`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/treino-c` | `/treino-c`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/treino-d` | `/treino-d`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/email-sent${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/treino-a${`?${string}` | `#${string}` | ''}` | `/treino-a${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/treino-b${`?${string}` | `#${string}` | ''}` | `/treino-b${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/treino-c${`?${string}` | `#${string}` | ''}` | `/treino-c${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/treino-d${`?${string}` | `#${string}` | ''}` | `/treino-d${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/email-sent`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-a` | `/treino-a`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-b` | `/treino-b`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-c` | `/treino-c`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/treino-d` | `/treino-d`; params?: Router.UnknownInputParams; };
    }
  }
}
